name: course_gnome_scrape
dependencies:
  http: ^0.12.0+1
  core:
    path: ../course_gnome/core
  html: ^0.13.3+3
  algolia: ^0.1.3+2
#  firebase_dart:
#    path: ../../firebase_dart
dev_dependencies:
  test: ^1.5.3
